In [1]:
from category_encoders import WOEEncoder

In [2]:
import pandas            as pd
import numpy             as np
import matplotlib.pyplot as plt 
import seaborn           as sns
import joblib            as jb
import xgboost           as xgb
import scipy.stats       as stats
import statsmodels.api   as sm

In [5]:
path        = ''   
path_data   = 'Data/'  
target      = 'produto'
path_automl = 'automl/'

In [6]:
df1_train     = pd.read_csv(path + path_data + 'treino.csv')
df1_test      = pd.read_csv(path + path_data + 'teste.csv')
df_submission = pd.DataFrame({target: np.zeros(df1_test.shape[0])})
df1_train.shape, df1_test.shape, df_submission.shape

((5700, 14), (3300, 13), (3300, 1))

In [74]:
X = df1_train.copy()
X['produto'] = X['produto'].map({'sim':1, 'não':0})

X.drop('produto', axis=1, inplace=True)

In [75]:
#from examples.source_data.loaders import get_mushroom_data
from sklearn.compose import ColumnTransformer
from category_encoders import TargetEncoder
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

import category_encoders as ce

In [ ]:
https://github.com/alteryx/categorical_encoding/blob/main/guides/notebooks/categorical-encoding-guide.ipynb

In [89]:
pipeline_ordinal = Pipeline(steps=[('imputer', SimpleImputer(strategy='constant', fill_value='missing'))
    ,('ord encoding', ce.ordinal.OrdinalEncoder())])


pipeline_loo = Pipeline(steps=[('imputer', SimpleImputer(strategy='constant', fill_value='missing'))
    ,('loo encoding', ce.LeaveOneOutEncoder())])

preprocessor = ColumnTransformer(
    transformers=[#('simple', pipeline_ordinal, ['educação','mês','dia', 'duração']), # 
                  ('targetbased', pipeline_loo, ['trabalho','estado civil'])
                 ], remainder='passthrough')


ct = ColumnTransformer(
    [
        ('target', TargetEncoder(cols=['who_opened', 'who_merged'], smoothing=100, min_samples_leaf=10), ['who_opened', 'who_merged'])
    ], remainder='passthrough', verbose_feature_names_out=True
)

#rf = RandomForestRegressor()

#pipe = Pipeline(steps=[('preprocessor', preprocessor),('regression', rf)])

#gs = GridSearchCV(pipe, param_grid=params, cv = cv)

#gs.fit(X, y)

pipe = Pipeline(steps=[('preprocessor', preprocessor)])


p = pipe.fit(X, y)

pd.DataFrame(p.fit_transform(X,y), )

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.373447,0.303259,36,ensino médio,não,não,não,telefone fixo,junho,quinta-feira,média,1,nenhum
1,0.218244,0.303259,32,básico,NaN,não,não,telefone móvel,julho,terça-feira,média,4,nenhum
2,0.324115,0.303259,49,NaN,não,sim,não,telefone fixo,maio,segunda-feira,longa,1,nenhum
3,0.324115,0.386015,28,NaN,não,não,não,telefone móvel,outubro,terça-feira,longa,1,nenhum
4,0.372793,0.385446,31,ensino técnico,não,NaN,NaN,telefone móvel,junho,quinta-feira,média,1,apenas um
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,0.324115,0.303259,44,NaN,NaN,não,não,telefone fixo,maio,segunda-feira,longa,2,nenhum
5696,0.218244,0.386015,36,básico,não,sim,não,telefone móvel,julho,quarta-feira,curta,1,nenhum
5697,0.323009,0.385446,28,graduação,não,sim,não,telefone móvel,dezembro,terça-feira,longa,3,apenas um
5698,0.218244,0.303259,51,básico,NaN,não,não,telefone fixo,maio,sexta-feira,longa,1,nenhum
5699,0.372793,0.385446,33,graduação,não,sim,não,telefone fixo,outubro,quinta-feira,média,3,nenhum

In [84]:
pd.DataFrame(preprocessor.fit_transform(X, y))

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.373447,0.303259,36,ensino médio,não,não,não,telefone fixo,junho,quinta-feira,média,1,nenhum
1,0.218244,0.303259,32,básico,NaN,não,não,telefone móvel,julho,terça-feira,média,4,nenhum
2,0.324115,0.303259,49,NaN,não,sim,não,telefone fixo,maio,segunda-feira,longa,1,nenhum
3,0.324115,0.386015,28,NaN,não,não,não,telefone móvel,outubro,terça-feira,longa,1,nenhum
4,0.372793,0.385446,31,ensino técnico,não,NaN,NaN,telefone móvel,junho,quinta-feira,média,1,apenas um
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5695,0.324115,0.303259,44,NaN,NaN,não,não,telefone fixo,maio,segunda-feira,longa,2,nenhum
5696,0.218244,0.386015,36,básico,não,sim,não,telefone móvel,julho,quarta-feira,curta,1,nenhum
5697,0.323009,0.385446,28,graduação,não,sim,não,telefone móvel,dezembro,terça-feira,longa,3,apenas um
5698,0.218244,0.303259,51,básico,NaN,não,não,telefone fixo,maio,sexta-feira,longa,1,nenhum
5699,0.372793,0.385446,33,graduação,não,sim,não,telefone fixo,outubro,quinta-feira,média,3,nenhum

In [ ]:

enc = WOEEncoder(cols=['Name_of_col','Another_name'])
training_set = enc.fit_transform(X_train, y_train)